[build]
  command = "ng build --prod && npm run scully"
  functions = "./functions"
  publish = "dist/static‚Äù
[dev]
  command = "npm run start"
  functions = "./functions"
  publish = "src"  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
